name: Lint Angular Code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches: 
      - main

jobs: 
  name: Lint
  lint:
    build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      -name: checkout
      uses: actions/checkout@v3

      -name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      
      -name: install dependencies
      run: npm install

      -name: Run eslint
      run: npm run eslint